const cards=[
  {word:"pose",phonetic:"/poʊz/",status:"hard",pos:"동사",vtype:"vt",def:"(위협을) 야기하다",enDef:"to present or cause a problem or danger",ex:"North Korea's missiles pose a threat to the entire region.\n북한의 미사일은 전 지역에 위협을 야기한다."},
  {word:"reserve",phonetic:"/rɪˈzɜːrv/",status:"hard",pos:"명사/동사",vtype:null,def:"보유량, 예비",enDef:"a supply kept for future use",ex:"The US keeps large reserves of oil for emergencies.\n미국은 비상사태를 위해 대규모 석유 보유량을 유지한다."},
  {word:"provide",phonetic:"/prəˈvaɪd/",status:"hard",pos:"동사",vtype:"vt",def:"제공하다, 공급하다",enDef:"to give or supply something needed",ex:"The government provides financial support to struggling families.\n정부는 어려운 가정에 재정 지원을 제공한다."},
  {word:"represent",phonetic:"/ˌrep.rɪˈzent/",status:"hard",pos:"동사",vtype:"vt",def:"대표하다, 차지하다",enDef:"to be an example of; to constitute",ex:"China represents nearly 20% of the world's population.\n중국은 전 세계 인구의 약 20%를 차지한다."},
  {word:"ease",phonetic:"/iːz/",status:"hard",pos:"동사/명사",vtype:"vt",def:"완화하다, 줄이다",enDef:"to make less severe or difficult",ex:"The new policy eased tensions between the two countries.\n새 정책은 두 나라 사이의 긴장을 완화했다."},
  {word:"dominate",phonetic:"/ˈdɒm.ɪ.neɪt/",status:"hard",pos:"동사",vtype:"vt",def:"지배하다, 압도하다",enDef:"to have control or power over",ex:"A few large companies dominate the global smartphone market.\n몇몇 대기업들이 글로벌 스마트폰 시장을 지배하고 있다."},
  {word:"compete",phonetic:"/kəmˈpiːt/",status:"hard",pos:"동사",vtype:"vi",def:"경쟁하다",enDef:"to strive against others for the same goal",ex:"Small businesses struggle to compete against global corporations.\n소기업들은 글로벌 대기업과 경쟁하기 위해 애쓴다."},
  {word:"rare earth",phonetic:"/reər ɜːrθ/",status:"hard",pos:"명사",vtype:null,def:"희토류",enDef:"a group of 17 metallic elements critical to modern technology",ex:"Electric vehicles require rare earth elements for their motors.\n전기차는 모터에 희토류 원소가 필요하다."},
  {word:"export control",phonetic:"/ˈek.spɔːrt kənˈtrəʊl/",status:"hard",pos:"명사",vtype:null,def:"수출 통제",enDef:"government restrictions on the sale of goods abroad",ex:"Export controls can slow down a rival country's technological development.\n수출 통제는 경쟁국의 기술 발전을 늦출 수 있다."},
  {word:"invasion",phonetic:"/ɪnˈveɪ.ʒən/",status:"hard",pos:"명사",vtype:null,def:"침공, 침략",enDef:"an act of entering another country by military force",ex:"The invasion shocked the international community.\n그 침공은 국제 사회에 충격을 주었다."},
  {word:"AGI",phonetic:"/ˌeɪ.dʒiːˈaɪ/",status:"hard",pos:"명사",vtype:null,def:"인공일반지능",enDef:"AI that can perform any intellectual task a human can do",ex:"Reaching AGI could change every industry on the planet.\nAGI에 도달하면 지구상의 모든 산업이 바뀔 수 있다."},
  {word:"compute",phonetic:"/kəmˈpjuːt/",status:"hard",pos:"명사/동사",vtype:null,def:"컴퓨팅 파워, 연산하다",enDef:"the processing power needed to train and run AI models",ex:"Training advanced AI models requires enormous amounts of compute.\n고급 AI 모델을 훈련하려면 엄청난 컴퓨팅 파워가 필요하다."},
  {word:"supply chain",phonetic:"/səˈplaɪ tʃeɪn/",status:"ok",pos:"명사",vtype:null,def:"공급망",enDef:"the network from raw materials to final product delivery",ex:"Many countries are trying to build more resilient supply chains.\n많은 나라들이 더 탄력적인 공급망을 구축하려 하고 있다."},
  {word:"regulate",phonetic:"/ˈreɡ.jʊ.leɪt/",status:"new",pos:"동사",vtype:"vt",def:"규제하다",enDef:"to control an activity or process by rules or laws",ex:"Governments are trying to regulate AI before it becomes too powerful.\n정부들은 AI가 너무 강력해지기 전에 규제하려 하고 있다."},
  {word:"integrate",phonetic:"/ˈɪn.tɪ.ɡreɪt/",status:"new",pos:"동사",vtype:"vt",def:"통합하다",enDef:"to combine parts into a whole system",ex:"China is integrating AI into its manufacturing and healthcare sectors.\n중국은 제조업과 의료 분야에 AI를 통합하고 있다."}
];
