const cards=[
  {word:"pose",phonetic:"/poʊz/",status:"hard",pos:"동사",vtype:"vt",def:"(위협을) 야기하다",enDef:"to present or cause a problem or danger",ex:"Rising sea levels pose a serious threat to coastal cities.\n해수면 상승은 해안 도시에 심각한 위협을 야기한다."},
  {word:"reserve",phonetic:"/rɪˈzɜːrv/",status:"hard",pos:"명사/동사",vtype:null,def:"보유량, 예비",enDef:"a supply kept for future use",ex:"Many countries are building reserves of critical minerals.\n많은 나라들이 핵심 광물 보유량을 구축하고 있다."},
  {word:"provide",phonetic:"/prəˈvaɪd/",status:"hard",pos:"동사",vtype:"vt",def:"제공하다, 공급하다",enDef:"to give or supply something needed",ex:"Solar energy provides a cleaner alternative to fossil fuels.\n태양에너지는 화석연료에 대한 더 깨끗한 대안을 제공한다."},
  {word:"represent",phonetic:"/ˌrep.rɪˈzent/",status:"hard",pos:"동사",vtype:"vt",def:"대표하다, 차지하다",enDef:"to be an example of; to constitute",ex:"Renewable energy now represents over 30% of global electricity.\n재생에너지는 이제 전 세계 전력의 30% 이상을 차지한다."},
  {word:"ease",phonetic:"/iːz/",status:"hard",pos:"동사/명사",vtype:"vt",def:"완화하다, 줄이다",enDef:"to make less severe or difficult",ex:"New trade deals could ease tensions over critical mineral supplies.\n새 무역협정이 핵심 광물 공급을 둘러싼 긴장을 완화할 수 있다."},
  {word:"dominate",phonetic:"/ˈdɒm.ɪ.neɪt/",status:"hard",pos:"동사",vtype:"vt",def:"지배하다, 압도하다",enDef:"to have control or power over",ex:"China dominates the global production of solar panels.\n중국은 태양광 패널 글로벌 생산을 지배하고 있다."},
  {word:"compete",phonetic:"/kəmˈpiːt/",status:"hard",pos:"동사",vtype:"vi",def:"경쟁하다",enDef:"to strive against others for the same goal",ex:"The US and EU are competing to build independent battery supply chains.\n미국과 EU는 독립적인 배터리 공급망 구축을 위해 경쟁하고 있다."},
  {word:"export control",phonetic:"/ˈek.spɔːrt kənˈtrəʊl/",status:"hard",pos:"명사",vtype:null,def:"수출 통제",enDef:"government restrictions on the sale of goods abroad",ex:"China's export controls on rare earths have alarmed the West.\n희토류에 대한 중국의 수출 통제가 서방을 놀라게 했다."},
  {word:"invasion",phonetic:"/ɪnˈveɪ.ʒən/",status:"hard",pos:"명사",vtype:null,def:"침공, 침략",enDef:"an act of entering another country by military force",ex:"The invasion disrupted global energy markets for years.\n그 침공은 수년간 글로벌 에너지 시장을 교란했다."},
  {word:"open source",phonetic:"/ˈoʊ.pən sɔːrs/",status:"hard",pos:"명사/형용사",vtype:null,def:"오픈소스",enDef:"software whose code is freely available for anyone to use or modify",ex:"Open source energy models are helping developing nations plan their grids.\n오픈소스 에너지 모델이 개발도상국들의 전력망 계획을 돕고 있다."},
  {word:"compute",phonetic:"/kəmˈpjuːt/",status:"hard",pos:"명사/동사",vtype:null,def:"컴퓨팅 파워, 연산하다",enDef:"the processing power needed to train and run AI models",ex:"Data centres for AI require enormous amounts of energy to compute.\nAI용 데이터센터는 연산을 위해 엄청난 양의 에너지가 필요하다."},
  {word:"sanction",phonetic:"/ˈsæŋk.ʃən/",status:"ok",pos:"명사/동사",vtype:null,def:"제재, 제재하다",enDef:"official penalty imposed on a country or person",ex:"Energy sanctions can be as powerful as military pressure.\n에너지 제재는 군사적 압박만큼 강력할 수 있다."},
  {word:"supply chain",phonetic:"/səˈplaɪ tʃeɪn/",status:"ok",pos:"명사",vtype:null,def:"공급망",enDef:"the network from raw materials to final product delivery",ex:"Countries are racing to secure their clean energy supply chains.\n각국은 청정에너지 공급망 확보를 위해 경쟁하고 있다."},
  {word:"AGI",phonetic:"/ˌeɪ.dʒiːˈaɪ/",status:"ok",pos:"명사",vtype:null,def:"인공일반지능",enDef:"AI that can perform any intellectual task a human can do",ex:"Some experts believe AGI could arrive within this decade.\n일부 전문가들은 AGI가 이번 10년 안에 도달할 수 있다고 믿는다."},
  {word:"energy transition",phonetic:"/ˈen.ər.dʒi trænˈzɪʃ.ən/",status:"new",pos:"명사",vtype:null,def:"에너지 전환",enDef:"the shift from fossil fuels to renewable energy sources",ex:"The energy transition is now a geopolitical race, not just a climate project.\n에너지 전환은 이제 기후 프로젝트가 아니라 지정학적 경주다."},
  {word:"critical minerals",phonetic:"/ˈkrɪt.ɪ.kəl ˈmɪn.ər.əlz/",status:"new",pos:"명사",vtype:null,def:"핵심 광물",enDef:"minerals essential to modern technology and national security",ex:"China controls the supply of most critical minerals the world needs.\n중국은 세계가 필요로 하는 대부분의 핵심 광물 공급을 통제한다."},
  {word:"electrostate",phonetic:"/ɪˈlek.troʊ.steɪt/",status:"new",pos:"명사",vtype:null,def:"전기국가",enDef:"a country that projects power through energy exports like solar panels and batteries",ex:"China has become the world's leading electrostate through solar and battery dominance.\n중국은 태양광과 배터리 지배를 통해 세계 선두 전기국가가 되었다."}
];
