const cards=[
  {word:"sanction",phonetic:"/ˈsæŋk.ʃən/",status:"hard",pos:"명사/동사",vtype:null,def:"제재, 제재하다",enDef:"official penalty imposed on a country or person",ex:"The US imposed sanctions on Russia after the invasion.\n미국은 침공 이후 러시아에 제재를 가했다."},
  {word:"pose",phonetic:"/poʊz/",status:"hard",pos:"동사",vtype:"vt",def:"(위협을) 야기하다",enDef:"to present or cause a problem or danger",ex:"China's military buildup poses a serious threat to Taiwan.\n중국의 군사력 증강은 대만에 심각한 위협을 야기한다."},
  {word:"reserve",phonetic:"/rɪˈzɜːrv/",status:"hard",pos:"명사/동사",vtype:null,def:"보유량, 예비",enDef:"a supply kept for future use",ex:"China holds the world's largest reserves of rare earth elements.\n중국은 세계 최대의 희토류 보유량을 갖고 있다."},
  {word:"provide",phonetic:"/prəˈvaɪd/",status:"hard",pos:"동사",vtype:"vt",def:"제공하다, 공급하다",enDef:"to give or supply something needed",ex:"Taiwan provides 90% of the world's advanced chips.\n대만은 전 세계 첨단 칩의 90%를 공급한다."},
  {word:"represent",phonetic:"/ˌrep.rɪˈzent/",status:"hard",pos:"동사",vtype:"vt",def:"대표하다, 차지하다",enDef:"to be an example of; to constitute",ex:"Semiconductors represent Korea's largest export industry.\n반도체는 한국의 최대 수출 산업을 차지한다."},
  {word:"tariff",phonetic:"/ˈtær.ɪf/",status:"hard",pos:"명사",vtype:null,def:"관세",enDef:"a tax on imported goods",ex:"Trump imposed 145% tariffs on Chinese goods.\n트럼프는 중국산 제품에 145% 관세를 부과했다."},
  {word:"ease",phonetic:"/iːz/",status:"hard",pos:"동사/명사",vtype:"vt",def:"완화하다, 줄이다",enDef:"to make less severe or difficult",ex:"The US agreed to ease export controls on some chips.\n미국은 일부 칩에 대한 수출 통제를 완화하기로 합의했다."},
  {word:"dominate",phonetic:"/ˈdɒm.ɪ.neɪt/",status:"hard",pos:"동사",vtype:"vt",def:"지배하다, 압도하다",enDef:"to have control or power over",ex:"China dominates global rare earth processing.\n중국은 전 세계 희토류 가공을 지배하고 있다."},
  {word:"compete",phonetic:"/kəmˈpiːt/",status:"hard",pos:"동사",vtype:"vi",def:"경쟁하다",enDef:"to strive against others for the same goal",ex:"The US and China compete for AI supremacy.\n미국과 중국은 AI 패권을 두고 경쟁한다."},
  {word:"semiconductor",phonetic:"/ˌsem.i.kənˈdʌk.tər/",status:"hard",pos:"명사",vtype:null,def:"반도체",enDef:"a material that conducts electricity under certain conditions",ex:"Semiconductors are the new oil of the 21st century.\n반도체는 21세기의 새로운 석유다."},
  {word:"rare earth",phonetic:"/reər ɜːrθ/",status:"hard",pos:"명사",vtype:null,def:"희토류",enDef:"a group of 17 metallic elements critical to modern technology",ex:"China controls over 60% of global rare earth processing.\n중국은 전 세계 희토류 가공의 60% 이상을 통제한다."},
  {word:"export control",phonetic:"/ˈek.spɔːrt kənˈtrəʊl/",status:"hard",pos:"명사",vtype:null,def:"수출 통제",enDef:"government restrictions on the sale of goods abroad",ex:"US export controls limit China's access to advanced chips.\n미국의 수출 통제는 중국의 첨단 칩 접근을 제한한다."},
  {word:"supply chain",phonetic:"/səˈplaɪ tʃeɪn/",status:"hard",pos:"명사",vtype:null,def:"공급망",enDef:"the network from raw materials to final product delivery",ex:"Taiwan's crisis would collapse the global supply chain.\n대만의 위기는 글로벌 공급망을 붕괴시킬 것이다."},
  {word:"invasion",phonetic:"/ɪnˈveɪ.ʒən/",status:"hard",pos:"명사",vtype:null,def:"침공, 침략",enDef:"an act of entering another country by military force",ex:"A full invasion of Taiwan could cost $10 trillion globally.\n대만 전면 침공은 전 세계적으로 10조 달러의 비용이 든다."},
  {word:"AGI",phonetic:"/ˌeɪ.dʒiːˈaɪ/",status:"new",pos:"명사",vtype:null,def:"인공일반지능",enDef:"AI that can perform any intellectual task a human can do",ex:"The US fears China could reach AGI first.\n미국은 중국이 AGI에 먼저 도달할 것을 두려워한다."},
  {word:"open source",phonetic:"/ˈoʊ.pən sɔːrs/",status:"new",pos:"명사/형용사",vtype:null,def:"오픈소스",enDef:"software whose code is freely available for anyone to use or modify",ex:"DeepSeek released its model as open source.\nDeepSeek은 모델을 오픈소스로 공개했다."},
  {word:"compute",phonetic:"/kəmˈpjuːt/",status:"new",pos:"명사/동사",vtype:null,def:"컴퓨팅 파워, 연산하다",enDef:"the processing power needed to train and run AI models",ex:"Whoever controls compute controls the future of AI.\n컴퓨팅 파워를 지배하는 자가 AI의 미래를 지배한다."}
];
